# add_websocket.py - adiciona endpoint WebSocket de ticks ao marketdata.py
path = r"D:\Projetos\finanalytics_ai_fresh\src\finanalytics_ai\interfaces\api\routes\marketdata.py"

WS_CODE = (
    "\n\n# __ WebSocket Live Ticks __\n"
    "import asyncio, json, subprocess as _sp\n\n"
    "@router.websocket('/live/ws/ticks/{ticker}')\n"
    "async def ws_ticks(websocket, ticker: str):\n"
    "    await websocket.accept()\n"
    "    container = 'finanalytics_redis'\n"
    "    channel = f'tape:ticks:{ticker.upper()}'\n"
    "    proc = None\n"
    "    try:\n"
    "        proc = await asyncio.create_subprocess_exec(\n"
    "            'docker','exec','-i',container,\n"
    "            'redis-cli','--no-auth-warning',\n"
    "            '-u','redis://localhost:6379/0',\n"
    "            'subscribe', channel,\n"
    "            stdout=asyncio.subprocess.PIPE,\n"
    "            stderr=asyncio.subprocess.DEVNULL,\n"
    "        )\n"
    "        buf = []\n"
    "        async for line in proc.stdout:\n"
    "            txt = line.decode().strip()\n"
    "            if not txt: continue\n"
    "            buf.append(txt)\n"
    "            if len(buf) == 3:\n"
    "                if buf[0] == 'message':\n"
    "                    try:\n"
    "                        await websocket.send_text(buf[2])\n"
    "                    except Exception:\n"
    "                        break\n"
    "                buf.clear()\n"
    "    except Exception:\n"
    "        pass\n"
    "    finally:\n"
    "        if proc and proc.returncode is None:\n"
    "            proc.terminate()\n"
    "        try: await websocket.close()\n"
    "        except: pass\n\n"
    "@router.websocket('/live/ws/tickers')\n"
    "async def ws_all_tickers(websocket):\n"
    "    await websocket.accept()\n"
    "    container = 'finanalytics_redis'\n"
    "    proc = None\n"
    "    try:\n"
    "        proc = await asyncio.create_subprocess_exec(\n"
    "            'docker','exec','-i',container,\n"
    "            'redis-cli','--no-auth-warning',\n"
    "            '-u','redis://localhost:6379/0',\n"
    "            'psubscribe','tape:ticks:*',\n"
    "            stdout=asyncio.subprocess.PIPE,\n"
    "            stderr=asyncio.subprocess.DEVNULL,\n"
    "        )\n"
    "        buf = []\n"
    "        async for line in proc.stdout:\n"
    "            txt = line.decode().strip()\n"
    "            if not txt: continue\n"
    "            buf.append(txt)\n"
    "            if len(buf) == 4:\n"
    "                if buf[0] == 'pmessage':\n"
    "                    try:\n"
    "                        await websocket.send_text(buf[3])\n"
    "                    except Exception:\n"
    "                        break\n"
    "                buf.clear()\n"
    "    except Exception:\n"
    "        pass\n"
    "    finally:\n"
    "        if proc and proc.returncode is None:\n"
    "            proc.terminate()\n"
    "        try: await websocket.close()\n"
    "        except: pass\n"
)

with open(path, encoding="utf-8") as f:
    content = f.read()

if "ws_ticks" in content:
    print("JA EXISTE")
else:
    with open(path, "a", encoding="utf-8") as f:
        f.write(WS_CODE)
    print("OK - WebSocket endpoints adicionados")
