-- Subscreve todos os tickers da carteira/watchlist em profit_subscribed_tickers.
-- Idempotente: ON CONFLICT (ticker, exchange) DO UPDATE preserva ticker existente,
-- só atualiza active=true para reativar caso tenha sido desativado.
--
-- ⚠️ ATENÇÃO 06/mai/2026: 18 tickers desta lista foram desativados por
-- InvalidTickerCallback durante boot do refactor Delphi-aligned (DLL Nelogica
-- rejeitou subscribe). Confirmado via 0 ticks em 7 dias. Lista:
--   AZUL4, EMBR3, ELET3, ELET6, BRFS3, CPLE5, CPLE6, MRFG3, PETZ3, PORT3,
--   RDNI3, REAG3, RNEW11, SRNA3, STBP3, ZAMP3, LVTC3, XPTO
-- Causa provável: corporate actions (BRFS3+MRFG3 → MBRF3, AZUL4 ch.11 2025, etc).
-- NÃO RE-RODAR este SQL as-is sem revisar essas linhas, ou serão reativadas.
-- Para auditoria: SELECT ticker, notes FROM profit_subscribed_tickers
--                 WHERE notes ILIKE '%INVALID 06/mai%';

INSERT INTO profit_subscribed_tickers (ticker, exchange, active, subscribe_book, priority, notes, updated_at)
VALUES
  -- Equities Bovespa (B)
  ('PETR4', 'B', TRUE, FALSE, 100, 'IBOV/Top10', NOW()),
  ('VALE3', 'B', TRUE, FALSE, 100, 'IBOV/Top10', NOW()),
  ('ITUB4', 'B', TRUE, FALSE, 100, 'IBOV/Top10', NOW()),
  ('BBAS3', 'B', TRUE, FALSE, 100, 'IBOV/Top10', NOW()),
  ('BBDC4', 'B', TRUE, FALSE, 100, 'IBOV/Top10', NOW()),
  ('B3SA3', 'B', TRUE, FALSE, 90, 'IBOV', NOW()),
  ('ABEV3', 'B', TRUE, FALSE, 90, 'IBOV', NOW()),
  ('EMBR3', 'B', TRUE, FALSE, 90, 'IBOV', NOW()),
  ('PETR3', 'B', TRUE, FALSE, 90, 'IBOV', NOW()),
  ('WEGE3', 'B', TRUE, FALSE, 90, 'IBOV', NOW()),
  ('RENT3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('PRIO3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('SBSP3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('BPAC11', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('ELET3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('SUZB3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('ITSA4', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('EQTL3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('MBRF3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('MGLU3', 'B', TRUE, FALSE, 80, 'IBOV', NOW()),
  ('LREN3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('RAIL3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('VBBR3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('GGBR4', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('RADL3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('HAPV3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('BBSE3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('RDOR3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('BRAV3', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('CPLE6', 'B', TRUE, FALSE, 70, 'IBOV', NOW()),
  ('ASAI3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('CSAN3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('VIVT3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('CYRE3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('CMIG4', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('TIMS3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('TOTS3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('ENGI11', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('ENEV3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('UGPA3', 'B', TRUE, FALSE, 60, 'IBOV', NOW()),
  ('BBDC3', 'B', TRUE, FALSE, 50, '', NOW()),
  ('KLBN11', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('MULT3', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('CSNA3', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('PSSA3', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('COGN3', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('ALOS3', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('POMO4', 'B', TRUE, FALSE, 50, '', NOW()),
  ('VIVA3', 'B', TRUE, FALSE, 50, '', NOW()),
  ('GOAU4', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('HYPE3', 'B', TRUE, FALSE, 50, 'IBOV', NOW()),
  ('SMFT3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('SANB11', 'B', TRUE, FALSE, 40, '', NOW()),
  ('AZZA3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('CXSE3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('DIRR3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('MRVE3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('USIM5', 'B', TRUE, FALSE, 40, '', NOW()),
  ('ELET6', 'B', TRUE, FALSE, 40, '', NOW()),
  ('BEEF3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('STBP3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('BRAP4', 'B', TRUE, FALSE, 40, '', NOW()),
  ('TAEE11', 'B', TRUE, FALSE, 40, '', NOW()),
  ('CURY3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('EGIE3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('CPFE3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('CPLE3', 'B', TRUE, FALSE, 40, '', NOW()),
  ('IGTI11', 'B', TRUE, FALSE, 30, '', NOW()),
  ('VAMO3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('CSMG3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('YDUQ3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('CEAB3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('ISAE4', 'B', TRUE, FALSE, 30, '', NOW()),
  ('AURE3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('AZUL4', 'B', TRUE, FALSE, 30, '', NOW()),
  ('IRBR3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('FLRY3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('TEND3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('SLCE3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('GGPS3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('PCAR3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('SRNA3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('BRKM5', 'B', TRUE, FALSE, 30, '', NOW()),
  ('CMIN3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('MOVI3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('RECV3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('SAPR11', 'B', TRUE, FALSE, 30, '', NOW()),
  ('SMTO3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('CVCB3', 'B', TRUE, FALSE, 30, '', NOW()),
  ('RAIZ4', 'B', TRUE, FALSE, 20, '', NOW()),
  ('GMAT3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('INTB3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ECOR3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('NEOE3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('PETZ3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ALUP11', 'B', TRUE, FALSE, 20, '', NOW()),
  ('EZTC3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('LWSA3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('SIMH3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('RAPT4', 'B', TRUE, FALSE, 20, '', NOW()),
  ('CBAV3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ANIM3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ORVR3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('SBFG3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ITUB3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('TTEN3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ALPA4', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ODPV3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('DXCO3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('MDIA3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('JHSF3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('BHIA3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('AMBP3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('VULC3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('BRSR6', 'B', TRUE, FALSE, 20, '', NOW()),
  ('ONCO3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('AMER3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('PLPL3', 'B', TRUE, FALSE, 20, '', NOW()),
  ('PORT3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('MDNE3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('MYPK3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('TUPY3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('ABCB4', 'B', TRUE, FALSE, 10, '', NOW()),
  ('HBSA3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('BPAN4', 'B', TRUE, FALSE, 10, '', NOW()),
  ('KEPL3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('CASH3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('SAPR4', 'B', TRUE, FALSE, 10, '', NOW()),
  ('UNIP6', 'B', TRUE, FALSE, 10, '', NOW()),
  ('GUAR3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('LEVE3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('MILS3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('TGMA3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('FRAS3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('GRND3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('KLBN4', 'B', TRUE, FALSE, 10, '', NOW()),
  ('VLID3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('LJQQ3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('LAVV3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('TFCO4', 'B', TRUE, FALSE, 10, '', NOW()),
  ('CAML3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('GFSA3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('EVEN3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('LOGG3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('BMOB3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('PRNR3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('ARML3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('SOJA3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('QUAL3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('RANI3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('SEER3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('POSI3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('LIGT3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('BRBI11', 'B', TRUE, FALSE, 10, '', NOW()),
  ('AGRO3', 'B', TRUE, FALSE, 10, '', NOW()),
  ('RCSL4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('PGMN3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SYNE3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('FESA4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('BLAU3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('JSLG3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('JALL3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('TRIS3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('WIZC3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('PNVL3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('HBOR3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('OPCT3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('AZEV4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('VTRU3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SHUL4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('AZTE3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('POMO3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('MTRE3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('CMIG3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('OIBR3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('TASA4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('VVEO3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('ZAMP3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('DESK3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('CSED3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('AMOB3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('MLAS3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('BMGB4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('TAEE4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('USIM3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('MELK3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('KLBN3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('MATD3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('PFRM3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('FIQE3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('HBRE3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('DASA3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SANB4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('RCSL3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SAPR3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('PINE4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('PTBL3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('ITSA3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('AERI3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SANB3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('ROMI3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('VITT3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('AZEV3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('TAEE3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('ENJU3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('BRAP3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('DEXP3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SEQL3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('IFCM3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('CSUD3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('BMEB4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('EUCA4', 'B', TRUE, FALSE, 5, '', NOW()),
  ('LOGN3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('BRST3', 'B', TRUE, FALSE, 5, '', NOW()),
  ('SCAR3', 'B', TRUE, FALSE, 5, '', NOW()),
  -- Futuros B3 (F)
  ('WINFUT', 'F', TRUE, FALSE, 100, 'Mini Indice Futuro', NOW()),
  ('WDOFUT', 'F', TRUE, FALSE, 100, 'Mini Dolar Futuro', NOW())
ON CONFLICT (ticker, exchange) DO UPDATE SET
  active = TRUE,
  priority = GREATEST(profit_subscribed_tickers.priority, EXCLUDED.priority),
  notes = CASE WHEN EXCLUDED.notes <> '' THEN EXCLUDED.notes ELSE profit_subscribed_tickers.notes END,
  updated_at = NOW();

-- Resumo
SELECT exchange, COUNT(*) AS tickers, COUNT(*) FILTER (WHERE active) AS ativos
FROM profit_subscribed_tickers
GROUP BY exchange
ORDER BY exchange;
